apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: conf-app
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: registry.digitalocean.com/checkmatez/conf-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: registry.digitalocean.com/checkmatez/conf-chat
      context: chat
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: registry.digitalocean.com/checkmatez/conf-web-client
      context: web-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx?'
            dest: .
