---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-db
          image: waisbrot/wait
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '32Mi'
          env:
            - name: TARGETS
              value: 'postgres-srv:5432'
        - name: init-auth-db
          image: postgres:11
          command: ['sh', '-c', 'createdb conf_app_auth || true']
          env:
            - name: PGHOST
              value: 'postgres-srv'
            - name: PGUSER
              value: 'postgres'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
        - name: init-auth-migrations
          image: checkmatez/conf-auth
          command: ['yarn', 'run', 'migrate']
          env:
            - name: DB_HOST
              value: 'postgres-srv'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'conf_app_auth'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: password
            - name: NODE_ENV
              value: 'production'
      containers:
        - name: auth
          image: checkmatez/conf-auth
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: PORT
              value: '3000'
            - name: DB_HOST
              value: 'postgres-srv'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'conf_app_auth'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: password
            - name: NODE_ENV
              value: 'production'
