---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      initContainers:
        - name: init-chat-db
          image: checkmatez/conf-chat
          command: ['yarn', 'run', 'migrate']
          env:
            - name: DB_HOST
              value: 'postgres-srv'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'conf_app_chat'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: password
            - name: NODE_ENV
              value: 'production'
      containers:
        - name: chat
          image: checkmatez/conf-chat
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: PORT
              value: '3000'
            - name: DB_HOST
              value: 'postgres-srv'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'conf_app_chat'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: password
            - name: NODE_ENV
              value: 'production'
